AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambdas

  Lambdas inside NX

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction01:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction01
      Handler: main.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld01:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello-world-01
            Method: get
    # Metadata: # Manage esbuild properties
    #   BuildMethod: esbuild
    #   BuildProperties:
    #     Minify: true
    #     Target: "es2020"
    #     Sourcemap: true
    #     EntryPoints:
    #     - app.ts
  # HelloWorldFunction02:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: HelloWorldFunction02
  #     Handler: main.handler
  #     Runtime: nodejs20.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld02:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /hello-world-02
  #           Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorld01Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function 01"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello-world-01/"
  HelloWorld01Function:
    Description: "Hello World Lambda Function 01 ARN"
    Value: !GetAtt HelloWorldFunction01.Arn
  HelloWorld01FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function 01"
    Value: !GetAtt HelloWorldFunction01Role.Arn
  HelloWorld02Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function 02"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello-world-02/"
  HelloWorld02Function:
    Description: "Hello World Lambda Function 02 ARN"
    Value: !GetAtt HelloWorldFunction02.Arn
  HelloWorld02FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function 02"
    Value: !GetAtt HelloWorldFunction02Role.Arn
